version: '3.0'

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php:/var/www/html
    depends_on:
      - php
    networks:
      - docker_net

  php:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_server
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
    networks:
      - docker_net

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_database_name
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    networks:
      - docker_net

networks:
  docker_net:
